services:
  frontend:
    build: ./frontend/my-app
    container_name: frontend
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    depends_on:
      backend:
        condition: service_started
    ports:
      - "3000:3000"

  backend:
    build: ./backend
    container_name: backend
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ML_SERVICE_URL=http://ml-service:8000
    depends_on:
      ml-service:
        condition: service_healthy
    ports:
      - "5000:5000"

  ml-service:
    build: ./ml-service
    container_name: ml-service
    environment:
      - PYTHONUNBUFFERED=1
    command: ["./start.sh"]
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request,sys; urllib.request.urlopen('http://localhost:8000/health'); sys.exit(0)"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "8000:8000"
